export enum PageName {
  Home = 'Home',
  Products = 'Products',
  Career = 'Career',
  Contact = 'Contact',
  About = 'About',
  News = 'News',
  Reference = 'Reference',
  ElMechElprom = 'ElMechElprom',
  Switchboard = 'Switchboard',
  Photovoltaic = 'Photovoltaic',
  ElectricalInstallation = 'ElectricalInstallation',
  Services = 'Servuces',
  Switchboards = 'Switchboards',
}
