export enum PageName {
  Home = 'Home',
  Products = 'Products',
  Career = 'Career',
  Contact = 'Contact',
  About = 'About',
  News = 'News',
  Reference = 'Reference',
  ElMechElprom = 'ElMechElprom',
  Switchboard = 'Switchboard',
  Photovoltaic = 'Photovoltaic',
  ElectricalInstallation = 'ElectricalInstallation',
  Services = 'Services',
  Switchboards = 'Switchboards',
  Service_1 = 'Service_1',
  Switchboard_1 = 'Switchboard_1',
  Photovoltaic_detail = 'Photovoltaic_detail',
}
